language: node_js

sudo: required

node_js:
  - '7'

install:
  - npm i create-elm-app -g

script: 
    - elm-app test
    - elm-app build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./build
  on:
    branch: master
